INSERT INTO burgers (burger_name) VALUES ("Original Slider");
INSERT INTO burgers (burger_name) VALUES ("Cheese Slider");
INSERT INTO burgers (burger_name) VALUES ("Double Cheese Slider");
-- INSERT INTO burgers (burger_name, devoured) VALUES ();
-- INSERT INTO burgers (burger_name, devoured) VALUES ();
-- INSERT INTO burgers (burger_name, devoured) VALUES ();
-- INSERT INTO burgers (burger_name) VALUES ("bacon");
-- INSERT INTO burgers (burger_name) VALUES ("cheeseburger");
-- INSERT INTO burgers (burger_name) VALUES ("chipotle");
INSERT INTO burgers (burger_name) VALUES ("Original Slider");
INSERT INTO burgers (burger_name) VALUES ("Cheese Slider");
INSERT INTO burgers (burger_name) VALUES ("Double Cheese Slider");